# This is a mini code-project by sunmmy.
# The feature would be:
# 1. Guess the random number generated by the programe,and the programe will tell the player
#if the number is higher or lower or just exactly the one.
# 2. There are 2 types of number-range,from 1 to 100 & from 1 to 1000.
# 3. The player has limited times to guess that number:in type(1-100) is 7,and in type(1-1000)
# is 10.
# 4. Player should first click the button to choose the type, then type number in the textfield,
# the program will display the result in the console.


import simplegui
import random
import math

game_range = 100

def new_game():
    global game_range, secret_number, guess_number 
    secret_number = random.randrange(0, game_range)
    
    if game_range == 100:
        guess_number = 7
    else:
        game_range == 1000:
        guess_number = 10
    print "You could choose a number between 0-", game_range
    print "You have only", guess_nmuber, "times remaining! Think carefully!"
        
def range100():
	game_range = 100
	new_game()
	
        
def range1000():
	game_range = 1000
	new_game()

def input_guess(guess):
	global guess_number
	guess_number -= 1 
	entered_number = int(guess)
	if guess_number == 0
		print " Time is out,try anoter one."
	elif entered_number>secret_number:
        print "Lower!"
    elif entered_number<secret_number:
        print "Higher!"
    elif:
        print "Correct!" 
	else 
	    print "You typed a wrong number you know!!!"
	
frame = simplegui.create_frame("Guess the number!", 200, 200)

frame.add_input("Guess",input_guess,100)
button1=frame.add_button("choose100",range100,100)
button2=frame.add_button("choose1000",range1000,100)

frame.start()

new_game


